In [23]:
from tensorflow.keras.preprocessing.text import one_hot


In [24]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [26]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [27]:
voc_size=10000

In [28]:
one_hot_rep=[one_hot(words,voc_size) for words in sent]

In [29]:
one_hot_rep

[[3556, 4634, 2817, 9575],
 [3556, 4634, 2817, 8775],
 [3556, 5008, 2817, 465],
 [7040, 2607, 3443, 1516, 9631],
 [7040, 2607, 3443, 1516, 2691],
 [8866, 3556, 2322, 2817, 6557],
 [6579, 7990, 1254, 1516]]

In [30]:
# word embedding rep

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences 
from tensorflow.keras.models import Sequential




In [31]:
import numpy as np 



In [32]:
sent_len=8
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_len)

In [33]:
print(embedded_docs)

[[   0    0    0    0 3556 4634 2817 9575]
 [   0    0    0    0 3556 4634 2817 8775]
 [   0    0    0    0 3556 5008 2817  465]
 [   0    0    0 7040 2607 3443 1516 9631]
 [   0    0    0 7040 2607 3443 1516 2691]
 [   0    0    0 8866 3556 2322 2817 6557]
 [   0    0    0    0 6579 7990 1254 1516]]


In [34]:
#feature representation 
dim=10

In [59]:
model = Sequential()

# Add the Embedding layer
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_length=sent_len))

# Manually build the model
model.build(input_shape=(None, sent_len))


# Compile the model
model.compile(optimizer='adam', loss='mse')


In [60]:
model.summary()

Model: "sequential_14"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_14 (Embedding)        │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [50]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step


array([[[-0.01263087,  0.02788614,  0.02909365, -0.01806581,
          0.03676151, -0.03833171, -0.03325941, -0.04070652,
          0.0420911 , -0.03588003],
        [-0.01263087,  0.02788614,  0.02909365, -0.01806581,
          0.03676151, -0.03833171, -0.03325941, -0.04070652,
          0.0420911 , -0.03588003],
        [-0.01263087,  0.02788614,  0.02909365, -0.01806581,
          0.03676151, -0.03833171, -0.03325941, -0.04070652,
          0.0420911 , -0.03588003],
        [-0.01263087,  0.02788614,  0.02909365, -0.01806581,
          0.03676151, -0.03833171, -0.03325941, -0.04070652,
          0.0420911 , -0.03588003],
        [ 0.04167621,  0.04832052, -0.03279705, -0.00624043,
          0.0100018 ,  0.00294293, -0.00611806,  0.02071879,
          0.02947998,  0.03950653],
        [ 0.00181364,  0.04695943,  0.04899994, -0.00439454,
          0.03323198,  0.01305487, -0.00582575, -0.01318168,
         -0.00657036,  0.02692667],
        [-0.0306941 , -0.04611732, -0.02566122, -0.0

In [51]:
embedded_docs[0]

array([   0,    0,    0,    0, 3556, 4634, 2817, 9575], dtype=int32)

In [61]:
model.predict(np.expand_dims(embedded_docs[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step


array([[[-0.01398085,  0.02669587, -0.02540733,  0.02519232,
         -0.01655383, -0.02051027, -0.01076254,  0.01231213,
          0.04583237,  0.02468106],
        [-0.01398085,  0.02669587, -0.02540733,  0.02519232,
         -0.01655383, -0.02051027, -0.01076254,  0.01231213,
          0.04583237,  0.02468106],
        [-0.01398085,  0.02669587, -0.02540733,  0.02519232,
         -0.01655383, -0.02051027, -0.01076254,  0.01231213,
          0.04583237,  0.02468106],
        [-0.01398085,  0.02669587, -0.02540733,  0.02519232,
         -0.01655383, -0.02051027, -0.01076254,  0.01231213,
          0.04583237,  0.02468106],
        [ 0.02414483,  0.01654584, -0.00779206, -0.0025539 ,
         -0.04948073,  0.0419862 , -0.01066235,  0.01279162,
          0.01634162,  0.02956733],
        [ 0.04402998,  0.00483308,  0.02614569, -0.00936335,
          0.00084933,  0.01525297, -0.00700973, -0.02540814,
         -0.02514566,  0.01035812],
        [-0.04526491, -0.03512763, -0.04952167, -0.0